apiVersion: 1

datasources:
  - name: Trade Postgres
    uid: trade-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: trade
    editable: false
    jsonData:
      database: trade
      postgresVersion: 1600
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: trade
